version: '3'
services:
  api:
    build: .
    ports:
     - "8000:8000"
    volumes:
      - ./:/opt/
    command: "python3 server.py"

  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./:/opt/
    command: "py.test -vv -x tests"
